//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cricketscore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class score
    {
        public int plno { get; set; }
        public string pname { get; set; }
        public int score1 { get; set; }
    }
}
